#!/bin/sh

cd $(dirname $0)

echo "==> Updating amcm"

git pull

echo "==> Updating addons"

if [ -e addons ]
then
  cd addons
  git pull
else
  git clone https://github.com/tomaszkiewicz/amcm-addons.git addons
fi