{{- define "argocdProject" }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .cluster.name }}
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: {{ .cluster.server }}
  sourceRepos:
  - '*'
  {{- $projectRoles := index .cluster "projectRoles" }}
  {{- if $projectRoles }}
  roles:{{ "\n" }}
  {{- $projectRoles | data.ToYAML | indent 2 }}
  {{- end }}
---
{{- end }}