{{- define "helmApplication" }}
{{- $name := index .app "name" }}
{{- if and (not $name) (index .app "addon") }}
{{- $name = .app.addon }}
{{- end }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}-{{ .cluster.name }}
  namespace: argocd
  {{- if and (index .app "cascadeDelete") }}
    {{- if .app.cascadeDelete }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
    {{- end }}
  {{- end }}
spec:
  project: {{ .cluster.name }}
  source:
{{- $namespace := $name }}
{{- $addon := index .app "addon" }}
{{- if $addon }}
    {{- $addonSettings := data.YAML (file.Read (printf "addons/%s.yaml" $addon)) }}
    {{- $namespace = index $addonSettings "namespace" }}
    repoURL: {{ $addonSettings.repoURL }}
    path: {{ $addonSettings.path }}
    {{- $targetRevision := index $addonSettings "targetRevision" }}
    {{- if $targetRevision }}
    targetRevision: {{ $targetRevision }}
    {{- end }}
    helm:
      {{- $releaseName := index $addonSettings "releaseName" }}
      {{- if not $releaseName }}
      {{- $releaseName = $name }}
      {{- end }}
      releaseName: {{ $releaseName }}
      {{- $parameters := index .app "parameters" }}
      {{- if $parameters }}
      parameters:
      {{- range $key, $value := $parameters }}
      - name: {{ $key }}
        value: {{ $value }}
      {{- end }}
      {{- end }}
      {{- if (index $addonSettings "values") }}
        {{- $values := $addonSettings.values | data.ToYAML }}
        {{- $settings := index .app "settings" }}
        {{- if $settings }}
          {{- range $key, $value := $settings }}
            {{- $values = regexp.Replace (printf "%s%s" "%SETTINGS_" $key) $value $values }}
          {{- end }}
        {{- end }}
      values: | {{ "\n" }}
        {{- $values | indent 8 }}
      {{- end }}
{{- else }}
    repoURL: {{ .cluster.repoURL }}
    path: {{ .app.chartPath }}
    {{- $targetRevision := index .app "targetRevision" }}
    {{- if $targetRevision }}
    targetRevision: {{ $targetRevision }}
    {{- end }}
    helm:
      valueFiles:
      {{ .app.valueFiles | data.ToYAML }}
{{- end }}
  destination:
    server: {{ .cluster.server }}
    {{- if not $namespace }}
      {{- $namespace = $name }}
    {{- end }}
    namespace: {{ $namespace }}
---
{{- end }}