{{- define "objectsGenerator" }}
{{- $paths := .paths -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amcm-objects-generator-{{ .cluster.name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .cluster.name }}
  source:
    repoURL: https://tomaszkiewicz.github.io/amcm-objects-generator/
    path: amcm-objects-generator
    helm:
      releaseName: amcm-objects-generator
      values: |
        namespaces:
      {{- $helmApplications := index . "helmApplications" }}
      {{- if $helmApplications }}
        {{- range $helmApplications }}
          {{- $name := index . "name" }}
          {{- if and (not $name) (index . "addon") }}
          {{- $name = .addon }}
          {{- end }}
          {{- $addon := index . "addon" }}
          {{- $addonFile := index . "addonFile" }}
          {{- if or $addon $addonFile }}
            {{- if not $addonFile }}
            {{- $addonFile = printf "addons/%s.yaml" $addon }}
            {{- end }}
            {{- $addonFile = regexp.Replace "\\$CLUSTER" $paths.cluster $addonFile }}
            {{- $addonFile = regexp.Replace "\\$REPO" $paths.repo $addonFile }}
            {{- $addonFile = regexp.Replace "\\$BASE" $paths.base $addonFile }}
            {{- $addonSettings := data.YAML (file.Read $addonFile) }}
            {{- $namespace := index $addonSettings "namespace" }}
            {{- if not $namespace }}
              {{- $namespace = $name }}
            {{- end }}
            {{- if and (ne $namespace "default") (ne $namespace "kube-system") }}
          - name: {{ $namespace }}
            {{- end }}
          {{- else }}
          {{- end }}
        {{- end }}
      {{- end }}
  destination:
    server: {{ .cluster.server }}
    namespace: kube-system
{{- $clusterDisableAutoSync := index .cluster "disableAutoSync" }}
{{- if not $clusterDisableAutoSync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
---
{{- end }}